<?php
if ($block->isMethodEupago()) { ?>

    <div id="checkout.mb_way.success">
        <div style="min-width: 300px;">
            <div align='center'>
                <table cellpadding="0" cellspacing="0" border="0"
                       style="width: 370px; color:#666; background-color: #f1f1f1; height: 50px; margin: 10px 0; border: 0px solid #d70510;">
                    <tbody>
                    <tr style=" font-size:small; border:0;">
                        <td style="border: 0; padding:5px; margin:0; background-color: #D80410; color: #f1f1f1; text-align: center; font-size:small;"
                            colspan="3">Pagamento por MB Way
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align:center;padding-top:5px; font-size: xx-small;border:0; border-top: 0px solid #ddd; background-color: #fff; color: #666"
                            colspan="3">
                            <img src='<?php echo $this->getViewFileUrl('Eupago_MbWay::images/eupago/logo_eupago.png'); ?>'
                                 alt="MbWay" style=" text-align: center; width: 50%; height: auto">
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align:center;padding-top:5px; font-size: xx-small;border:0; border-top: 0px solid #ddd; background-color: #fff; color: #666">
                            <b>Order: <?php echo $block->getData('order_id'); ?></b>
                        </td>
                        <td style="text-align:center;padding-top:5px; font-size: xx-small;border:0; border-top: 0px solid #ddd; background-color: #fff; color: #666">
                            <b>Valor: <?php echo $block->getData('grand_total'); ?>€</b>
                        <td style="text-align:center;padding-top:5px; font-size: xx-small;border:0; border-top: 0px solid #ddd; background-color: #fff; color: #666">
                            <b> Número MB Way: <?php echo $block->getData('phone_number'); ?></b>
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align:center;padding-top:5px; font-size: xx-small;border:0; border-top: 0px solid #ddd; background-color: #fff; color: #666"
                            colspan="3">
                            <img src='<?php echo $this->getViewFileUrl('Eupago_MbWay::images/eupago/mbway/MBWAY_RGB_positivo_s.png'); ?>'
                                 alt="MbWay" style=" text-align: center;">
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<?php } ?>